name: Post-processing


on:
  pull_request:
    types:
      - closed

jobs:
  post-processing:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to website
        uses: actions/checkout@v4
        with:
          ref: website
          path: .website

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Copy llpkgstore.json to root
        continue-on-error: true
        run: |
          # ignore error
          ls .website .website/_website/public
          cp .website/_website/public/llpkgstore.json . 2>/dev/null
          rm -rf .website

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
      - name: Skip Cache Parser Tool
        run: |
          go env -w GOPRIVATE=github.com/MeteorsLiu/llpkgstore
      - name: Set up Parser Tool
        run: |
          go install -v github.com/MeteorsLiu/llpkgstore/cmd/llpkgstore@gha-test
      - name: Run post-processing process
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          llpkgstore postprocessing

      - name: Checkout website branch
        uses: actions/checkout@v4
        with:
            ref: website
            path: .website

      - name: Move llpkgstore.json to website
        run: |
            mv llpkgstore.json .website/_website/public

      - name: Commit and push changes
        working-directory: .website/_website
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add public/llpkgstore.json
            git commit -m "Update llpkgstore.json"
            git push